In [23]:
#1st program
#A* algo

def aStarAlgo(start_node, stop_node):
    

    open_set = set(start_node) # {A}, len{open_set}=1
    closed_set = set()
    g = {} # store the distance from starting node
    parents = {}
    g[start_node] = 0
    parents[start_node] = start_node # parents['A']='A"

    while len(open_set) > 0 :
        n = None

        for v in open_set: # v='B'/'F'
            if n == None or g[v] + heuristic(v) < g[n] + heuristic(n):
                n = v # n='A'

        if n == stop_node or Graph_nodes[n] == None:
            pass #Continue bcz we need to traverse backtracking
        else:
            for (m, weight) in get_neighbors(n):
             # nodes 'm' not in first and last set are added to first
             # n is set its parent
                if m not in open_set and m not in closed_set:
                    open_set.add(m)      # m=B weight=6 {'F','B','A'} len{open_set}=2
                    parents[m] = n       # parents={'A':A,'B':A} len{parent}=2
                    g[m] = g[n] + weight # g={'A':0,'B':6, 'F':3} len{g}=2
                    
                    # calculating the total heuristic values for all nodes and then find the shortest path


            #for each node m,compare its distance from start i.e g(m) to the
            #from start through n node
                else:
                    if g[m] > g[n] + weight:
                    #update g(m)
                        g[m] = g[n] + weight
                    #change parent of m to n
                        parents[m] = n

                    #if m in closed set,remove and add to open
                        if m in closed_set:
                            closed_set.remove(m)
                            open_set.add(m)

        if n == None:
            print('Path does not exist!')
            return None

        # if the current node is the stop_node
        # then we begin reconstructin the path from it to the start_node
        if n == stop_node:
            path = []

            while parents[n] != n:
                path.append(n)
                n = parents[n]

            path.append(start_node)

            path.reverse()

            print('Path found: {}'.format(path))
            return path


        # remove n from the open_list, and add it to closed_list
        # because all of his neighbors were inspected
        open_set.remove(n)# {'F','B'} len=2
        closed_set.add(n) #{A} len=1

    print('Path does not exist!')
    return None

#define fuction to return neighbor and its distance
#from the passed node
def get_neighbors(v):
    if v in Graph_nodes:
        return Graph_nodes[v]
    else:
        return None
#for simplicity we ll consider heuristic distances given
#and this function returns heuristic distance for all nodes
 
def heuristic(n):
    H_dist = {
       'A': 10,
        'B': 8,
        'C': 5,
        'D': 7,
        'E': 3,
        'F': 6,
        'G': 5,
        'H': 3,
        'I': 1,
        'J': 0
    }

    return H_dist[n]

#Describe your graph here
Graph_nodes = {
    
     'A': [('B', 6), ('F', 3)],
    'B': [('C', 3), ('D', 2)],
    'C': [('D', 1), ('E', 5)],
    'D': [('C', 1), ('E', 8)],
    'E': [('I', 5), ('J', 5)],
    'F': [('G', 1),('H', 7)] ,
    'G': [('I', 3)],
    'H': [('I', 2)],
    'I': [('E', 5), ('J', 3)],

}
aStarAlgo('A', 'J')


Path found: ['A', 'F', 'G', 'I', 'J']


['A', 'F', 'G', 'I', 'J']

In [18]:
#3rd program
#candidate elimination

import numpy as np
import pandas as pd 
data=pd.DataFrame(data=pd.read_csv('cand.csv'))
concepts=np.array(data.iloc[:,0:-1])
print("CON =",concepts)
target=np.array(data.iloc[:,-1])
print("TAR=",target)

def learn(concepts,target):
    specific_h=concepts[0].copy()
    print("specific=",specific_h)
    general_h=[["?" for i in range(len(specific_h))] for i in range(len(specific_h))]
    print("general=",general_h)
    for i,h in enumerate(concepts):
        
        if target[i]=="yes":
            for x in range(len(specific_h)):
                if h[x]!=specific_h[x]:
                    specific_h[x]='?'
                    general_h[x][x]='?'
        if target[i]=="no":
            for x in range(len(specific_h)):
                if h[x]!=specific_h[x]:
                    general_h[x][x]=specific_h[x]
                else:
                    general_h[x][x]='?'
    indices=[i for i,val in enumerate(general_h) if val==['?','?','?','?','?']]
    for i in indices:
        general_h.remove(['?','?','?','?','?'])
    return specific_h,general_h

s_final,g_final=learn(concepts,target)
print("Final S;",s_final,sep="\n")
print("Final G;",g_final,sep="\n")
data.head()

CON = [['sunny' 'warm' 'high' 'strong' 'warm' 'same']
 ['rainy' 'cold' 'high' 'strong' 'warm' 'change']
 ['sunny' 'warm' 'high' 'strong' 'cool' 'change']]
TAR= ['yes' 'no' 'yes']
specific= ['sunny' 'warm' 'high' 'strong' 'warm' 'same']
general= [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]
Final S;
['sunny' 'warm' 'high' 'strong' '?' '?']
Final G;
[['sunny', '?', '?', '?', '?', '?'], ['?', 'warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]


sunny  warm normal  strong warm.1    same  yes
0  sunny  warm   high  strong   warm    same  yes
1  rainy  cold   high  strong   warm  change   no
2  sunny  warm   high  strong   cool  change  yes

In [20]:
#5th program
#ANN algo

import numpy as np
epochs=2
inputLayerSize,hiddenLayerSize,outputLayerSize=2,3,1
L=0.1

x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])

def Sigmoid(x): return 1/(1+np.exp(-x))
def Sigmoid_(x):return x*(1-x)
hidden_weights=np.random.uniform(size=(inputLayerSize,hiddenLayerSize))
print('-----Hidden Layer Weights-----')
print(hidden_weights)
print('xxxxxxxxxxxxx')
output_weights=np.random.uniform(size=(hiddenLayerSize,outputLayerSize))
print('-----output Layer Weights-----')
print('xxxxxxxxxxxxx')
for i in range(epochs):
    Hidden_result=Sigmoid(np.dot(x,hidden_weights))
    print('-----Hidden Layer Weights-----')
    print('Hidden_result')
    print('xxxxxxxxxxxxx')
    output=np.dot(Hidden_result,output_weights)
    print('-----output-----')
    print(output)
    print('xxxxxxxxxxxxx')
    Error=y-output
    print('-----Error-----')
    print(Error)
    print('xxxxxxxxxxxxx')
    dz=Error*L
    print('-----change in Error-----')
    print(dz)
    print('xxxxxxxxxxxxx')
    output_weights+=Hidden_result.T.dot(dz)
    print('-----change in output_weights-----') 
    print(output_weights)
    print('xxxxxxxxxxxxx')
    dHidden_result=dz.dot(output_weights.T)*Sigmoid_(Hidden_result)
    print('-----change in Hidden result-----')
    print(dHidden_result)
    print('xxxxxxxxxxxxx')
    hidden_weights+=x.T.dot(dHidden_result)
    print('-----change in Hidden weights-----')
    print(hidden_weights)

-----Hidden Layer Weights-----
[[0.26316589 0.67757535 0.04105897]
 [0.54955546 0.54305788 0.39222317]]
xxxxxxxxxxxxx
-----output Layer Weights-----
xxxxxxxxxxxxx
-----Hidden Layer Weights-----
Hidden_result
xxxxxxxxxxxxx
-----output-----
[[0.18055131]
 [0.21936437]
 [0.19385591]
 [0.23119738]]
xxxxxxxxxxxxx
-----Error-----
[[-0.18055131]
 [ 0.78063563]
 [ 0.80614409]
 [-0.23119738]]
xxxxxxxxxxxxx
-----change in Error-----
[[-0.01805513]
 [ 0.07806356]
 [ 0.08061441]
 [-0.02311974]]
xxxxxxxxxxxxx
-----change in output_weights-----
[[0.13622209]
 [0.11485346]
 [0.32069132]]
xxxxxxxxxxxxx
-----change in Hidden result-----
[[-0.00061488 -0.00051842 -0.00144753]
 [ 0.00246746  0.002084    0.00602391]
 [ 0.00269838  0.00206812  0.00646036]
 [-0.00067042 -0.00046714 -0.00176923]]
xxxxxxxxxxxxx
-----change in Hidden weights-----
[[0.26519385 0.67917633 0.0457501 ]
 [0.5513525  0.54467475 0.39647785]]
-----Hidden Layer Weights-----
Hidden_result
xxxxxxxxxxxxx
-----output-----
[[0.28588343]
 [0

In [1]:
from pprint import pprint
import pandas as pd

csvfile=pd.read_csv('id3.csv')
df_tennis=pd.DataFrame(csvfile)
def entropy(probs):
    import math
    return sum([-prob*math.log(prob,2)for prob in probs])

def entropy_of_list(a_list):
    from collections import Counter
    cnt=Counter(x for x in a_list)
    print("No and Yes Classes:", a_list.name,cnt)
    num_instances=len(a_list)*1.0
    probs=[x/num_instances for x in cnt.values()]
    return entropy(probs)
total_entropy=entropy_of_list(df_tennis['Play Tennis'])
print("Entropy of given Play Tennis Data Set:",total_entropy)

def information_gain(df, split_attribute_name,target_attribute_name,trace=0):
    print("Information Gain Calculation of",split_attribute_name)
    df_split=df.groupby(split_attribute_name)
  #takes a DataFrame of attributes, and quantities the entropy of a target attribute after performing a split along the values of another attributes
#print(df_split.groups)
    for name,group in df_split:
        print(name)
        print(group)
    #calculate entropy for target attributes,as well as proportion of Obs in each data-split
    nobs=len(df.index)*1.0
    #print("NOBS",nobs)
    df_agg_ent=df_split.agg({target_attribute_name:[entropy_of_list, lambda x: len(x) / nobs]})[target_attribute_name]
    #print["FAGGED",df_agg_ent]
    df_agg_ent.columns=['Entropy','PropObservations']
    #if traced: #helps understand what fxn is doing:
    #calculate Information Gain:
    new_entropy=sum(df_agg_ent['Entropy']*df_agg_ent['PropObservations'])
    old_entropy=entropy_of_list(df[target_attribute_name])
    return old_entropy-new_entropy

def id3(df,target_attribute_name,attribute_names,default_class=None): #tally target attribute
    from collections import Counter
    cnt=Counter(x for x in df[target_attribute_name])#class of yes or no
    #first check: Is this split of the dataset homogeneous?
    if len(cnt)==1:
        return next(iter(cnt))
    #second check: is the split of the dataset empty?
    #if yes, return a default value
    elif df.empty or (not attribute_names):
        return default_class
    #otherwise: this dataset is ready to divide up
    else:
        #(index_of_max)# most common value of target attribute in dataset
        default_class=max(cnt.keys())
        #choose best attribute to split on
        gainz=[information_gain(df,attr,target_attribute_name)
              for attr in attribute_names]
        index_of_max=gainz.index(max(gainz))
        best_attr=attribute_names[index_of_max]
        #create an empty tree, to be populated in a moment
        tree={best_attr:{}}
        remaining_attribute_names=[
            i for i in attribute_names if i!=best_attr]
        #split dataset
        #on each split,recursively call this algorithm
        #populate the empty tree with subtrees which are the result of the recursive call
        for attr_val,data_subset in df.groupby(best_attr):
            subtree=id3(data_subset,target_attribute_name,remaining_attribute_names,default_class)
            tree[best_attr][attr_val]=subtree
        return tree

#predicitng attributes
attribute_names=list(df_tennis.columns)
print("List of attributes:",attribute_names)
attribute_names.remove('Play Tennis')# remove the class attribute
print("Predicting attributes:",attribute_names)
#tree construction
tree=id3(df_tennis,'Play Tennis',attribute_names)
print("\n\n The Resultant Decesion Tree is:\n")
pprint(tree)

No and Yes Classes: Play Tennis Counter({'Yes': 9, 'No': 5})
Entropy of given Play Tennis Data Set: 0.9402859586706309
List of attributes: ['Day', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis']
Predicting attributes: ['Day', 'Outlook', 'Temperature', 'Humidity', 'Wind']
Information Gain Calculation of Day
D1
  Day Outlook Temperature Humidity  Wind Play Tennis
0  D1   Sunny         Hot     High  Weak          No
D10
   Day Outlook Temperature Humidity  Wind Play Tennis
9  D10    Rain        Mild   Normal  Weak         Yes
D11
    Day Outlook Temperature Humidity    Wind Play Tennis
10  D11   Sunny        Mild   Normal  Strong         Yes
D12
    Day   Outlook Temperature Humidity    Wind Play Tennis
11  D12  Overcast        Mild     High  Strong         Yes
D13
    Day   Outlook Temperature Humidity  Wind Play Tennis
12  D13  Overcast         Hot   Normal  Weak         Yes
D14
    Day Outlook Temperature Humidity    Wind Play Tennis
13  D14    Rain        Mild     High  S

In [28]:
import pandas as pd
from pprint import pprint
from sklearn.feature_selection import mutual_info_classif
from collections import Counter

def id3(df, target_attribute, attribute_names, default_class=None):
    cnt=Counter(x for x in df[target_attribute])
    if len(cnt)==1:
        return next(iter(cnt))
    
    elif df.empty or (not attribute_names):
         return default_class

    else:
        gainz = mutual_info_classif(df[attribute_names],df[target_attribute],discrete_features=True)
        index_of_max=gainz.tolist().index(max(gainz))
        best_attr=attribute_names[index_of_max]
        tree={best_attr:{}}
        remaining_attribute_names=[i for i in attribute_names if i!=best_attr]
        
        for attr_val, data_subset in df.groupby(best_attr):
            subtree=id3(data_subset, target_attribute, remaining_attribute_names,default_class)
            tree[best_attr][attr_val]=subtree
        
        return tree
    

df=pd.read_csv("id3.csv")

attribute_names=df.columns.tolist()
print("List of attribut name")

attribute_names.remove("Play Tennis")

for colname in df.select_dtypes("object"):
    df[colname], _ = df[colname].factorize()
    
print(df)

tree= id3(df,"Play Tennis", attribute_names)
print("The tree structure")
pprint(tree)

List of attribut name
    Day  Outlook  Temperature  Humidity  Wind  Play Tennis
0     0        0            0         0     0            0
1     1        0            0         0     1            0
2     2        1            0         0     0            1
3     3        2            1         0     0            1
4     4        2            2         1     0            1
5     5        2            2         1     1            0
6     6        1            2         1     1            1
7     7        0            1         0     0            0
8     8        0            2         1     0            1
9     9        2            1         1     0            1
10   10        0            1         1     1            1
11   11        1            1         0     1            1
12   12        1            0         1     0            1
13   13        2            1         0     1            0
The tree structure
{'Day': {0: 0,
         1: 0,
         2: 1,
         3: 1,
         4: 1,